
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineFanShop.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class FanKviz
{

    public int ID_pitanje { get; set; }

    public string pitanje { get; set; }

    public string odgovor { get; set; }

    public int ID_fransiza_FK { get; set; }



    public virtual FransizaProizvoda FransizaProizvoda { get; set; }

}

}
