
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineFanShop.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Korisnik
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Korisnik()
    {

        this.Kosarica = new HashSet<Kosarica>();

        this.ListaZelja = new HashSet<ListaZelja>();

        this.RecenzijaProizvoda = new HashSet<RecenzijaProizvoda>();

    }


    public int ID_korisnik { get; set; }

    public string ime { get; set; }

    public string prezime { get; set; }

    public string korisnickoIme { get; set; }

    public string lozinka { get; set; }

    public string email { get; set; }

    public string adresa { get; set; }

    public string brojMobitela { get; set; }

    public bool obavijest { get; set; }

    public int ID_uloga_FK { get; set; }



    public virtual UlogaKorisnika UlogaKorisnika { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kosarica> Kosarica { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ListaZelja> ListaZelja { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RecenzijaProizvoda> RecenzijaProizvoda { get; set; }

}

}
