

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineFanShop.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EntitiesOnlineFanShop : DbContext
{
    public EntitiesOnlineFanShop()
        : base("name=EntitiesOnlineFanShop")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<FanKviz> FanKviz { get; set; }

    public virtual DbSet<FransizaProizvoda> FransizaProizvoda { get; set; }

    public virtual DbSet<Korisnik> Korisnik { get; set; }

    public virtual DbSet<Kosarica> Kosarica { get; set; }

    public virtual DbSet<ListaZelja> ListaZelja { get; set; }

    public virtual DbSet<Ponuda> Ponuda { get; set; }

    public virtual DbSet<Primka> Primka { get; set; }

    public virtual DbSet<Proizvod> Proizvod { get; set; }

    public virtual DbSet<RecenzijaProizvoda> RecenzijaProizvoda { get; set; }

    public virtual DbSet<Skladiste> Skladiste { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<UlogaKorisnika> UlogaKorisnika { get; set; }

    public virtual DbSet<VelicinaProizvoda> VelicinaProizvoda { get; set; }

    public virtual DbSet<VrstaProizvoda> VrstaProizvoda { get; set; }

}

}

