
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineFanShop.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Ponuda
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ponuda()
    {

        this.Kosarica = new HashSet<Kosarica>();

        this.ListaZelja = new HashSet<ListaZelja>();

        this.RecenzijaProizvoda = new HashSet<RecenzijaProizvoda>();

    }


    public int ID_ponuda { get; set; }

    public int kolicina { get; set; }

    public double ocjena { get; set; }

    public int ID_proizvod_FK { get; set; }

    public Nullable<double> cijena { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kosarica> Kosarica { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ListaZelja> ListaZelja { get; set; }

    public virtual Proizvod Proizvod { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RecenzijaProizvoda> RecenzijaProizvoda { get; set; }

}

}
