
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineFanShop.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Primka
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Primka()
    {

        this.Skladiste = new HashSet<Skladiste>();

    }


    public int ID_primka { get; set; }

    public System.DateTime datum { get; set; }

    public string imeDobavljaca { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Skladiste> Skladiste { get; set; }

}

}
