
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineFanShop.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class RecenzijaProizvoda
{

    public int ID_recenzija { get; set; }

    public int ocjena { get; set; }

    public string komentar { get; set; }

    public int ID_korisnik_FK { get; set; }

    public int ID_ponuda_FK { get; set; }



    public virtual Korisnik Korisnik { get; set; }

    public virtual Ponuda Ponuda { get; set; }

}

}
