
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineFanShop.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Skladiste
{

    public int ID_proizvod { get; set; }

    public int ID_primka { get; set; }

    public int kolicina { get; set; }



    public virtual Primka Primka { get; set; }

    public virtual Proizvod Proizvod { get; set; }

}

}
